# permissions for end users to edit virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-editor-role
rules:
- apiGroups:
  - hobbyfarm.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hobbyfarm.io
  resources:
  - virtualmachines/status
  verbs:
  - get
